version: "3.7"

services:
  router1:
    build:
      context: .
      dockerfile: router.Dockerfile
    container_name: router1
    network_mode: bridge
    ports:
      - "50051:50051"
    command: ["/usr/lib/frr/gnmi-gateway", "--grpc-addr=0.0.0.0:50051"]
